#!/usr/bin/env python3
"""Generate the Q14 32-band synthesis cosine matrix.

This is deliberately a build-time tool: the 386SX never evaluates trig and
the decoder uses only signed integer multiply/add in its hot path.
"""
import math
import sys

if len(sys.argv) != 2:
    raise SystemExit(f"usage: {sys.argv[0]} OUTPUT")

with open(sys.argv[1], "w", encoding="ascii") as out:
    out.write("/* Generated by tools/gen_mp2_synth_table.py; do not edit. */\n")
    out.write("static const int16_t mp2_synth_cos_q14[32][32] = {\n")
    for n in range(32):
        # ISO synthesis modulation: V[n] = sum(S[k] *
        # cos(pi/64 * (2*k+1) * (n-16))).  The ring/tap code consumes
        # V[0..31]; the remaining half follows by symmetry.
        row = [round(16384 * math.cos(math.pi * (2*k + 1) * (n - 16) / 64))
               for k in range(32)]
        out.write("    {" + ", ".join(map(str, row)) + "}")
        out.write(",\n" if n != 31 else "\n")
    out.write("};\n")
